# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: trigger from dev side test

on:
  push:
    branches: [ master ]

jobs:

  build:
  
   runs-on: windows-latest
  
   steps:
   - uses: actions/checkout@v2
   - name: Set up JDK 1.8
     uses: actions/setup-java@v1
     with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
   - name: Build with Maven
     run: mvn -B package --file pom.xml
   - name: trigger in window #Will trigger workflow on EftiarHossain repo
     uses: actions/github-script@v6    
     with:
      github-token: ${{ secrets.ACCESS_TOKEN_TRIGGER }}
      script: |
        await github.rest.actions.createWorkflowDispatch({
        owner: 'AfrinaZahan',
        repo: 'selenium-practice',
        workflow_id: 'QA_1.yml',
        github_token: ${{ secrets.ACCESS_TOKEN }}
        ref: 'main'})
        
  build1:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: trigger qa1 repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: AfrinaZahan
        repo: selenium-practice
     #   ref: master
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: QA_1.yml
      
    - name: trigger qa2 repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: AfrinaZahan
        repo: selenium-practice
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: QA_2.yml
     
     
        

  build2:

    #runs-on: windows-latest
    runs-on: ubuntu-latest
    needs: build1

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: trigger qa2.2 repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: AfrinaZahan
        repo: selenium-practice
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: QA_2.yml
        
    - name: trigger another repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: AfrinaZahan
        repo: SeleniumAssignment
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: maven.yml
        
    - name: trigger another one repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: soheldef123
        repo: selenium
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: qa.yml
      
        
  build3:
    
      runs-on: windows-latest
      needs: build2
      steps:
      
      - name: wait
        run: sleep 5
      
     
